name: Setup Ubuntu Docker with ngrok

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Pull Ubuntu image
      run: docker pull ubuntu:latest

    - name: Run Ubuntu container
      run: |
        docker run -d --name ubuntu-container -p 22:22 ubuntu:latest sleep infinity

    - name: Install SSH in the container
      run: |
        docker exec ubuntu-container apt-get update
        docker exec ubuntu-container apt-get install -y openssh-server
        docker exec ubuntu-container service ssh start

    - name: Configure SSH
      run: |
        docker exec ubuntu-container mkdir /root/.ssh
        echo "${{ secrets.SSH_PUBLIC_KEY }}" | docker exec -i ubuntu-container bash -c 'cat > /root/.ssh/authorized_keys'

    - name: Install ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt-get update
        sudo apt-get install ngrok

    - name: Start ngrok
      run: |
        ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        ngrok tcp 22 --log=stdout > ngrok.log &
        sleep 5
        NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
        echo "ngrok URL: $NGROK_URL"
        echo "NGROK_URL=$NGROK_URL" >> $GITHUB_ENV

    - name: Display ngrok URL
      run: echo "ngrok URL is ${{ env.NGROK_URL }}"

    - name: Test SSH Connection
      run: |
        NGROK_HOST=$(echo ${{ env.NGROK_URL }} | cut -d'/' -f3 | cut -d':' -f1)
        NGROK_PORT=$(echo ${{ env.NGROK_URL }} | cut -d'/' -f3 | cut -d':' -f2)
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} -p $NGROK_PORT root@$NGROK_HOST "echo 'SSH connection successful!'"
